version: '3.7'

services:
  armstrong:
    image: ${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
    ports:
      - '8080:3000'
